### ISSUE TITLE
Powershell(3)-脚本执行基础小节中的脚本优先问题

### ISSUE THREAD

**Issue by zhutougg** [rootclay/Powershell-Attack-Guide#1]
set pathext
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

执行顺序应该是越靠前优先级越高，所以exe优先级比bat高。文中说反了

**Comment by rootclay** [comment]
是的，这里应该有一个修改PATHEXT文件执行顺序的过程，我的错误，谢谢指正
